export const properties = [
  {
    id: 1,
    title: "Luxe Loft Living",
    price: "$385,000",
    location: "North Legon, Accra",
    bedrooms: 4,
    bathrooms: 4,
    area: "305 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/o1.jfif",
    additionalImages: [
      "",
      "",
      "",
      "",
      ""],
    description: "This exquisite 4-bedroom luxury home in the heart of North Legon combines contemporary design with functional living spaces. Featuring high ceilings, modern finishes, and an open-plan layout, this property is perfect for families seeking comfort in one of Accra's most sought-after neighborhoods. The home boasts premium fixtures throughout, with ample natural lighting and ventilation. Close to international schools, shopping centers, and major access routes.",
    amenities: [
      "24-Hour Security",
      "Walled and Gated Compound",
      "Backup Generator",
      "Water Storage Tank",
      "Fitted Kitchen with Cabinets",
      "Master Bedroom En-suite",
      "Guest Washroom",
      "Spacious Car Park",
      "Paved Compound",
      "Servant's Quarters"
    ],
    status: "For Sale",
    propertyType: "Luxury Homes",
    featured: false
  },
  {
    id: 2,
    title: "Elegant Family Home",
    price: "$390,000",
    location: "Adjiringanor, East Legon, Accra",
    bedrooms: 5,
    bathrooms: 6,
    area: "275 sq m",
    image: "https://raw.githubusercontent.com/webeddies/Properties/refs/heads/main/12-cover.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Situated in the prestigious Adjiringanor enclave of East Legon, this stunning 5-bedroom family residence offers elegance and sophistication. The property features spacious living areas, a modern kitchen with top-of-the-line appliances, and beautifully appointed bedrooms. The master suite is a sanctuary with walk-in closets and a luxurious bathroom. Perfect for executives and families who value quality finishes, privacy, and convenience in Accra's diplomatic hub.",
    amenities: [
      "Gated Community",
      "Solar Power Backup",
      "Mechanized Borehole",
      "Air Conditioning Throughout",
      "Built-in Wardrobes",
      "Jacuzzi in Master Bathroom",
      "Home Office Space",
      "CCTV Security System",
      "Garden with Irrigation",
      "4-Car Garage",
      "Staff Accommodation",
      "Intercom System"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: true
  },
  {
    id: 3,
    title: "Luxurious Island Property",
    price: "$2,150,000",
    location: "Axim",
    bedrooms: 8,
    bathrooms: 9,
    area: "632 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/island%20property.jpg",
    additionalImages: ["", "", "", "", ""],
    description: "An extraordinary private island estate offering unparalleled luxury and seclusion on the stunning Western Coast. This magnificent 8-bedroom property features breathtaking ocean views, private beach access, and world-class amenities. Perfect as a luxury resort, corporate retreat, or exclusive family compound. The property includes multiple entertainment pavilions, infinity pools, and meticulously landscaped tropical gardens. Boat access and helipad available. This is a rare opportunity to own a piece of paradise.",
    amenities: [
      "Private Island Location",
      "Private Beach Access",
      "Infinity Swimming Pool",
      "Boat Dock and Jetty",
      "Helipad",
      "Solar and Generator Power",
      "Desalination Plant",
      "Restaurant and Bar Facilities",
      "Staff Quarters Complex",
      "Commercial Kitchen",
      "Entertainment Pavilion",
      "Water Sports Equipment Storage",
      "24/7 Security Personnel",
      "Satellite Internet"
    ],
    status: "For Sale",
    propertyType: "Luxury Homes",
    featured: false
  },
  {
    id: 4,
    title: "Affordable Comfort",
    price: "$286,000",
    location: "Adenta, Accra",
    bedrooms: 4,
    bathrooms: 4,
    area: "288 sq m",
    image: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    additionalImages: ["", "", "", "", ""],
    description: "This well-designed 4-bedroom family home in Adenta offers excellent value for money without compromising on quality. The property features a practical layout with all bedrooms en-suite, a spacious living area, and a modern kitchen. Located in a peaceful neighborhood with good road access, this home is ideal for young professionals and growing families. The area is well-served by schools, markets, and healthcare facilities, making it perfect for everyday living.",
    amenities: [
      "Perimeter Wall Fence",
      "Security Gate",
      "Standby Generator Provision",
      "Polytank Water Storage",
      "All Rooms En-suite",
      "Guest Toilet",
      "Tiled Throughout",
      "Kitchen Cabinets",
      "Pop Ceilings",
      "Paved Parking Space",
      "Boys' Quarters"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 5,
    title: "Contemporary Condo",
    price: "$1,890/month",
    location: "Lakeside Estate, Accra",
    bedrooms: 3,
    bathrooms: 3,
    area: "430 sq m",
    image: "https://www.edenoasisrealty.com/wp-content/uploads/2024/12/DJI_0533.jpg",
    additionalImages: ["", "", "", "", ""],
    description: "Experience modern lakeside living in this beautifully finished 3-bedroom apartment within the exclusive Lakeside Estate. The property offers stunning water views, contemporary finishes, and access to world-class estate facilities. With 24-hour security, well-maintained common areas, and a serene environment, this rental is perfect for expatriates and senior executives seeking comfort and convenience. The estate features jogging paths, recreational facilities, and is minutes from Airport Residential Area.",
    amenities: [
      "Estate Security 24/7",
      "Swimming Pool Access",
      "Gymnasium",
      "Generator Backup",
      "Fully Air-conditioned",
      "Fitted Kitchen with Appliances",
      "Servant's Room",
      "Balcony with Lake View",
      "2 Covered Parking Bays",
      "Clubhouse Access",
      "Children's Play Area",
      "Jogging Track"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 6,
    title: "Akyem Hideaway",
    price: "$220/night",
    location: "Akim Oda",
    bedrooms: 3,
    bathrooms: 2,
    area: "260 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u7.jfif",
    status: "For Rent",
    propertyType: "Short Stays",
    featured: true
  },
  {
    id: 7,
    title: "Delacoas Villa",
    price: "$4,350/month",
    location: "Oyibi, Accra",
    bedrooms: 6,
    bathrooms: 7,
    area: "515 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/k1.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "An architectural masterpiece in the serene Oyibi community, this 6-bedroom luxury villa redefines opulent living. The property boasts grand living spaces, a chef's kitchen, cinema room, and luxurious master suite with spa bathroom. Set on expansive landscaped grounds with a swimming pool and outdoor entertainment area, this villa is perfect for diplomatic missions, corporate executives, or affluent families. The property includes smart home features, solar power, and staff quarters.",
    amenities: [
      "Gated Estate Security",
      "Swimming Pool",
      "Cinema/Media Room",
      "Solar Power System",
      "Central Air Conditioning",
      "Smart Home Automation",
      "CCTV Surveillance",
      "Landscaped Gardens",
      "Outdoor Kitchen/BBQ Area",
      "Wine Cellar",
      "4 Staff Rooms",
      "Gym Room",
      "Study/Library",
      "5-Car Garage"
    ],
    status: "For Rent",
    propertyType: "Luxury Homes",
    featured: true
  },
  {
    id: 8,
    title: "Luxury Penthouse Suite",
    price: "$325,000",
    location: "East Legon Hills, Accra",
    bedrooms: 4,
    bathrooms: 4,
    area: "315 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/l1.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "This sophisticated 4-bedroom home in East Legon Hills combines luxury with practicality. Featuring contemporary architecture, premium finishes, and panoramic views of Accra, this property is designed for modern living. The open-plan living area flows seamlessly to outdoor spaces, perfect for entertaining. Located in a quiet cul-de-sac within minutes of A&C Mall, restaurants, and international schools. An ideal investment or family home.",
    amenities: [
      "24-Hour Security",
      "Backup Generator",
      "Borehole Water Supply",
      "All Rooms En-suite",
      "Walk-in Closets",
      "Modern Kitchen",
      "Air Conditioning",
      "Balconies with Views",
      "Laundry Room",
      "Covered Parking",
      "Storage Room",
      "Guest Toilet"
    ],
    status: "For Sale",
    propertyType: "Luxury Homes",
    featured: false
  },
  {
    id: 9,
    title: "Fully Furnished Harmony Home",
    price: "$235,000",
    location: "Ejisu, Kumasi",
    bedrooms: 3,
    bathrooms: 3,
    area: "285 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/n1.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Move-in ready 3-bedroom furnished home in the growing Ejisu area. This property comes fully equipped with quality furniture, appliances, and fixtures, making it perfect for buyers seeking immediate occupancy. The home features a modern design with ceramic tiles throughout, a fitted kitchen, and well-appointed bathrooms. The quiet neighborhood offers a peaceful environment while remaining close to Kumasi's amenities and the Accra-Kumasi highway.",
    amenities: [
      "Fully Furnished",
      "Kitchen Appliances Included",
      "Air Conditioners in Bedrooms",
      "Flat Screen TV",
      "Dining Set",
      "Security Fence",
      "Water Storage Tank",
      "All Rooms En-suite",
      "Tiled Throughout",
      "Paved Compound",
      "2-Car Parking",
      "Boys' Quarters"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 10,
    title: "Luxury Villa with Riverside View",
    price: "$415,000",
    location: "Akosombo",
    bedrooms: 4,
    bathrooms: 4,
    area: "350 sq m",
    image: "https://anaarkutu.com/wp-content/uploads/2022/04/DJI_0410-1.jpg",
    additionalImages: ["", "", "", "", ""],
    description: "Wake up to breathtaking views of the Volta River in this stunning 4-bedroom villa in Akosombo. This property offers a unique blend of luxury and nature, featuring floor-to-ceiling windows, expansive terraces, and direct river access. Perfect as a vacation home, weekend retreat, or rental investment in Ghana's premier tourism destination. The villa includes a private dock, landscaped gardens, and modern amenities throughout. Experience tranquil waterfront living at its finest.",
    amenities: [
      "Waterfront Location",
      "Private River Access",
      "Boat Dock",
      "Infinity Pool",
      "Outdoor Entertaining Deck",
      "Floor-to-Ceiling Windows",
      "Central Air Conditioning",
      "Solar Power Backup",
      "Landscaped Gardens",
      "BBQ Area",
      "Staff Quarters",
      "Security Fence",
      "4-Car Parking",
      "Generator House"
    ],
    status: "For Sale",
    propertyType: "Luxury Homes",
    featured: true
  },
  {
    id: 11,
    title: "Sunset Crest Manor",
    price: "$1,200/month",
    location: "Ogbodjo, Accra",
    bedrooms: 2,
    bathrooms: 2,
    area: "480 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/s8.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "This cozy 2-bedroom apartment in Ogbodjo offers comfortable living in a developing neighborhood with good road access. The property features a modern design with both bedrooms en-suite, a functional kitchen, and a spacious living area. Ideal for young couples or small families seeking affordable quality rental accommodation. The area is experiencing rapid development with new shopping centers and improved infrastructure, making it a smart choice for renters.",
    amenities: [
      "Gated Compound",
      "Security Personnel",
      "Generator Backup",
      "Both Bedrooms En-suite",
      "Guest Washroom",
      "Modern Kitchen",
      "Tiled Floors",
      "Air Conditioning Ready",
      "Water Storage",
      "2 Parking Spaces",
      "Balcony",
      "Prepaid Meter"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: true
  },
  {
    id: 12,
    title: "Kofymens Apartments",
    price: "$800/month",
    location: "Bohyen, Kumasi",
    bedrooms: 2,
    bathrooms: 2,
    area: "360 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/s4.jpg",
    additionalImages: ["", "", "", "", ""],
    description: "Affordable and practical 2-bedroom apartment in the Bohyen area of Kumasi. This well-maintained unit offers good value for money with modern finishes, ample storage, and a safe neighborhood. Perfect for professionals working in Kumasi or small families seeking budget-friendly accommodation. The area has good access to the city center, markets, schools, and other essential amenities. Water and power are reliable in this location.",
    amenities: [
      "Walled Compound",
      "Security Gate",
      "Both Rooms En-suite",
      "Kitchen with Cabinets",
      "Tiled Throughout",
      "Water Supply",
      "Parking Space",
      "Guest Washroom",
      "Balcony",
      "Standby Generator",
      "Prepaid Electricity"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 13,
    title: "K.K. Beachfront Executive Lodge",
    price: "$1,900/month",
    location: "Prampram, Accra",
    bedrooms: 2,
    bathrooms: 2,
    area: "330 sq m",
    image: "https://raw.githubusercontent.com/webeddies/Properties/refs/heads/main/10-cover.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Experience coastal living in this beautiful 2-bedroom beachfront property in Prampram. Wake up to ocean views and the sound of waves from this fully furnished executive apartment. Perfect for expatriates, executives, or anyone seeking a peaceful retreat from city life while maintaining easy access to Accra. The property features modern amenities, direct beach access, and resort-style living. Enjoy weekend beach life or use as a permanent seaside residence.",
    amenities: [
      "Beachfront Location",
      "Direct Beach Access",
      "Fully Furnished",
      "Ocean View Balcony",
      "Swimming Pool Access",
      "24/7 Security",
      "Generator Backup",
      "Air Conditioning",
      "Modern Kitchen with Appliances",
      "DSTV Ready",
      "WiFi Ready",
      "2 Parking Bays",
      "Laundry Service Available"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 14,
    title: "Brick & Budget",
    price: "$166,000",
    location: "Frafraha, Accra",
    bedrooms: 2,
    bathrooms: 2,
    area: "225 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t16.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "An excellent starter home for first-time buyers or investment property in the Frafraha area. This compact 2-bedroom house offers practical living spaces with both bedrooms en-suite. The property sits on its own plot with room for future expansion. The neighborhood is developing rapidly with improving infrastructure and amenities. This is a solid investment opportunity at an attractive price point for those looking to enter the property market.",
    amenities: [
      "Fenced Compound",
      "Security Gate",
      "Both Bedrooms En-suite",
      "Kitchen Space",
      "Living/Dining Area",
      "Tiled Floors",
      "Water Storage",
      "Parking Space",
      "Own Plot",
      "Expansion Potential",
      "Outer Toilet"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 15,
    title: "Cedar Grove Court",
    price: "$182,000",
    location: "Avatime Amedzofe, Ho",
    bedrooms: 4,
    bathrooms: 5,
    area: "305 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/s2.jpg",
    additionalImages: ["", "", "", "", ""],
    description: "Discover mountain living in this exceptional 4-bedroom home in Avatime Amedzofe, Ghana's highest human settlement. This property offers cool climate, stunning mountain views, and a peaceful environment perfect for retirement, vacation home, or eco-tourism investment. The home features quality construction with modern amenities while embracing the natural beauty of the Volta Region. Wake up above the clouds in this unique mountain retreat, just hours from Accra.",
    amenities: [
      "Mountain Views",
      "Cool Climate Location",
      "All Bedrooms En-suite",
      "Modern Kitchen",
      "Large Veranda",
      "Water Storage System",
      "Solar Panel Ready",
      "Fruit Trees",
      "Garden Space",
      "Parking Area",
      "Security Fence",
      "Guest Washroom",
      "Store Room"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 16,
    title: "Fully Furnished Executive Enclave",
    price: "$1,650/month",
    location: "Essikado, Takoradi",
    bedrooms: 2,
    bathrooms: 3,
    area: "500 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t3.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Premium furnished 2-bedroom apartment in the heart of Takoradi's Essikado neighborhood. This executive property comes with high-quality furniture, appliances, and finishes throughout. Perfect for oil and gas professionals, expatriates, or business executives seeking turnkey accommodation in the Western Region capital. The apartment is located close to shopping centers, hospitals, and the beach, offering convenience and comfort for modern living.",
    amenities: [
      "Fully Furnished",
      "Kitchen Appliances Included",
      "Air Conditioned Throughout",
      "DSTV Installed",
      "WiFi Included",
      "Generator Backup",
      "Water Storage",
      "Security Service",
      "All Rooms En-suite",
      "Guest Washroom",
      "Covered Parking",
      "Balcony",
      "Washing Machine"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: true
  },
  {
    id: 17,
    title: "Cozy Comfort",
    price: "$175,000",
    location: "Anaji, Takoradi",
    bedrooms: 2,
    bathrooms: 3,
    area: "280 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u11.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "This well-maintained 2-bedroom home in Anaji offers affordable homeownership in Takoradi. The property features modern finishes with three bathrooms including a guest washroom, making it perfect for a small family or as a rental investment property. Anaji is a growing residential area with good access to the city center, schools, markets, and the harbor. The home sits on a decent plot with parking space and room for landscaping.",
    amenities: [
      "Fenced Compound",
      "Security Gate",
      "Both Bedrooms En-suite",
      "Guest Washroom",
      "Kitchen with Cabinets",
      "Tiled Floors",
      "Pop Ceiling",
      "Water Storage Tank",
      "Paved Parking",
      "Front Porch",
      "Boys' Quarters",
      "Good Road Access"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 18,
    title: "Eban Gardens Home",
    price: "$1,380/month",
    location: "Effiduase, Koforidua",
    bedrooms: 2,
    bathrooms: 2,
    area: "320 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t8.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Elegant 2-bedroom rental home in the scenic Effiduase area of Koforidua. This property offers a serene environment with modern amenities, perfect for professionals working in the Eastern Region capital or families seeking a peaceful lifestyle. The home features quality finishes, a well-equipped kitchen, and beautiful garden space. Koforidua offers a cooler climate, lower cost of living, and easy access to Accra via the motorway, making it an attractive residential option.",
    amenities: [
      "Gated Compound",
      "Security Service",
      "Generator Provision",
      "Both Bedrooms En-suite",
      "Modern Kitchen",
      "Living and Dining Areas",
      "Tiled Throughout",
      "Water Storage",
      "Garden Space",
      "2-Car Parking",
      "Guest Washroom",
      "Porch Area"
    ],
    status: "For Rent",
    propertyType: "Luxury Homes",
    featured: true
  },
  {
    id: 19,
    title: "The Orchid Nest",
    price: "$2,300/month",
    location: "Tema Community 25, Accra",
    bedrooms: 4,
    bathrooms: 4,
    area: "360 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t9.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Spacious 4-bedroom apartment in the well-planned Tema Community 25. This property offers modern family living with all bedrooms en-suite, a large living area, and contemporary finishes throughout. The community features excellent infrastructure, proximity to the harbor, shopping centers, schools, and healthcare facilities. Ideal for families working in Tema or seeking organized community living with good security and reliable utilities. The apartment comes with covered parking and servants' quarters.",
    amenities: [
      "Estate Security 24/7",
      "All Bedrooms En-suite",
      "Spacious Living Area",
      "Modern Kitchen",
      "Guest Washroom",
      "Air Conditioning",
      "Generator Backup",
      "Water Storage",
      "Covered Parking",
      "Balcony",
      "Servant's Quarters",
      "DSTV Ready",
      "Prepaid Meter"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 20,
    title: "Budget Family Home",
    price: "$175,000",
    location: "Oduom, Kumasi",
    bedrooms: 3,
    bathrooms: 3,
    area: "275 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t6.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Affordable 3-bedroom family home in Oduom, one of Kumasi's developing residential areas. This property offers excellent value with all bedrooms en-suite, a functional layout, and quality construction. Perfect for first-time homebuyers, young families, or as an investment property in Ghana's second-largest city. The area has good road access, growing commercial activities, and proximity to schools and healthcare facilities. A practical choice for those seeking homeownership in Kumasi.",
    amenities: [
      "Walled Compound",
      "Security Gate",
      "All Bedrooms En-suite",
      "Kitchen with Cabinets",
      "Guest Washroom",
      "Tiled Floors",
      "Pop Ceiling",
      "Water Storage",
      "Parking Space",
      "Front Porch",
      "Back Garden",
      "Boys' Quarters Option"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 21,
    title: "Hilltop Escape Apartments",
    price: "$2,100/month",
    location: "Aburi",
    bedrooms: 3,
    bathrooms: 3,
    area: "460 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t2.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Experience the fresh mountain air and cooler climate of Aburi in this stunning 3-bedroom hilltop apartment. Located in Ghana's famous botanical gardens town, this property offers breathtaking views, tranquil surroundings, and a perfect escape from Accra's heat. The apartment features spacious rooms, modern finishes, and large windows that frame the scenic landscape. Ideal for executives seeking a weekend retreat or families wanting a healthier living environment while remaining within commuting distance to Accra.",
    amenities: [
      "Mountain Views",
      "Cool Climate",
      "All Bedrooms En-suite",
      "Modern Kitchen",
      "Spacious Balconies",
      "24-Hour Security",
      "Generator Backup",
      "Water Storage System",
      "Parking for 2 Cars",
      "Garden Access",
      "Guest Washroom",
      "Tiled Throughout",
      "Air Circulation (Natural Cooling)"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 22,
    title: "Timeless Family Classic",
    price: "$265,000",
    location: "New Achimota, Accra",
    bedrooms: 4,
    bathrooms: 5,
    area: "230 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/s5.jpg",
    additionalImages: ["", "", "", "", ""],
    description: "Classic 4-bedroom family home in the established New Achimota neighborhood. This well-built property offers traditional architectural charm combined with modern conveniences. With 5 bathrooms including a guest washroom, the home is perfect for growing families. Located near the Achimota Forest Reserve, Golf Club, and top international schools, this property offers both tranquility and convenience. The area boasts excellent infrastructure with reliable utilities and good road networks.",
    amenities: [
      "Walled Compound",
      "Security Gate",
      "All Bedrooms En-suite",
      "Guest Washroom",
      "Spacious Kitchen",
      "Family Dining Area",
      "Front Porch",
      "Back Garden",
      "Water Storage Tank",
      "Generator Provision",
      "3-Car Parking",
      "Boys' Quarters",
      "Tiled Throughout"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 23,
    title: "Ayaneese Serenity Villa",
    price: "$580,000",
    location: "Airport Residential, Accra",
    bedrooms: 5,
    bathrooms: 6,
    area: "420 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t1.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Exceptional 5-bedroom luxury villa in the prestigious Airport Residential Area. This architectural masterpiece features contemporary design, premium finishes, and smart home technology throughout. The property includes a master suite with walk-in closet and spa bathroom, gourmet kitchen, entertainment spaces, and beautifully landscaped grounds. Located in Accra's diplomatic enclave, this villa offers ultimate privacy, security, and proximity to international schools, embassies, and upscale shopping. A statement property for discerning buyers.",
    amenities: [
      "Gated Community",
      "Smart Home System",
      "Central Air Conditioning",
      "Solar Power System",
      "CCTV Surveillance",
      "Swimming Pool",
      "Landscaped Gardens",
      "Master Suite with Jacuzzi",
      "Walk-in Closets",
      "Modern Chef's Kitchen",
      "Home Office/Study",
      "Entertainment Room",
      "4 Staff Quarters",
      "4-Car Garage",
      "Backup Generator"
    ],
    status: "For Sale",
    propertyType: "Luxury Homes",
    featured: true
  },
  {
    id: 24,
    title: "Seaside Terraced Duplexes with BQ",
    price: "$1,420/month",
    location: "Winneba",
    bedrooms: 4,
    bathrooms: 4,
    area: "410 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t19.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Beautiful 4-bedroom terraced duplex with sea views in the coastal town of Winneba. This modern property features two floors of comfortable living space plus a self-contained boys' quarters. Perfect for families seeking beach lifestyle while maintaining modern amenities. The duplex offers a private compound within a secure estate, just minutes from the beach. Winneba offers excellent schools including the University of Education, hospitals, and a relaxed coastal atmosphere, making it ideal for academics and families.",
    amenities: [
      "Sea Views",
      "Estate Security",
      "Boys' Quarters (Self-Contained)",
      "All Bedrooms En-suite",
      "Duplex Design",
      "Modern Kitchen",
      "Guest Washroom",
      "Balconies",
      "Generator Backup",
      "Water Storage",
      "3-Car Parking",
      "Paved Compound",
      "Close to Beach"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 25,
    title: "The Modal Townhouse",
    price: "$185,000",
    location: "Kwabenya, Accra",
    bedrooms: 3,
    bathrooms: 3,
    area: "380 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t7.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Modern 3-bedroom townhouse in the rapidly developing Kwabenya area. This property offers contemporary living at an affordable price, featuring all bedrooms en-suite, a spacious living area, and a functional kitchen. Kwabenya has experienced significant infrastructure development, with improved roads, commercial centers, and good access to both Accra and the Aburi mountains. An excellent choice for first-time buyers or investors looking for capital appreciation in a growing neighborhood.",
    amenities: [
      "Gated Compound",
      "Security Gate",
      "All Bedrooms En-suite",
      "Modern Kitchen",
      "Open Plan Living",
      "Guest Washroom",
      "Tiled Floors",
      "Pop Ceiling",
      "Water Storage",
      "Parking for 2 Cars",
      "Porch Area",
      "Generator Ready",
      "Room for Extension"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 26,
    title: "The Platinum Townhouse",
    price: "$3,250/month",
    location: "Ridge, Accra",
    bedrooms: 5,
    bathrooms: 6,
    area: "480 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t4.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Ultra-luxurious 5-bedroom townhouse in the heart of Ridge, Accra's most prestigious residential area. This exquisite property features top-of-the-line finishes, designer interiors, and state-of-the-art amenities. Located within walking distance of government ministries, high commissions, and upscale restaurants, this townhouse is perfect for diplomatic staff, corporate executives, or affluent families. The property includes a private rooftop terrace with panoramic city views, home automation, and 24/7 concierge service.",
    amenities: [
      "Prime Ridge Location",
      "24/7 Concierge Service",
      "Smart Home Automation",
      "Central Air Conditioning",
      "Rooftop Terrace",
      "City Views",
      "Designer Kitchen",
      "Wine Cellar",
      "Home Theater",
      "Gym Room",
      "Solar + Generator Backup",
      "CCTV Security",
      "4-Car Basement Parking",
      "Staff Quarters",
      "Elevator Access"
    ],
    status: "For Rent",
    propertyType: "Luxury Homes",
    featured: true
  },
  {
    id: 27,
    title: "Modern Minimalist Home",
    price: "$438,000",
    location: "Obuasi",
    bedrooms: 6,
    bathrooms: 6,
    area: "360 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t13.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Striking contemporary 6-bedroom home in Obuasi, Ghana's historic mining town. This architecturally impressive property showcases minimalist design with clean lines, large windows, and premium finishes throughout. Perfect for mining executives, business owners, or affluent families in the Ashanti Region. The home features expansive living spaces, a modern kitchen, and a master suite with luxury amenities. Obuasi offers good infrastructure, quality schools, and investment opportunities in Ghana's gold mining heartland.",
    amenities: [
      "Contemporary Architecture",
      "All Bedrooms En-suite",
      "Master Suite with Dressing Room",
      "Gourmet Kitchen",
      "Open Plan Living",
      "Home Office",
      "Solar Power System",
      "Generator House",
      "CCTV Security",
      "Landscaped Compound",
      "Swimming Pool Ready",
      "4-Car Garage",
      "2 Staff Quarters",
      "Water Treatment System"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: true
  },
  {
    id: 28,
    title: "Maple Court Studio Flat",
    price: "$215/night",
    location: "Kotei, Kumasi",
    bedrooms: 3,
    bathrooms: 3,
    area: "180 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t11.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Cozy short-stay accommodation in Kotei, one of Kumasi's upscale neighborhoods. This fully furnished 3-bedroom property offers comfortable lodging for business travelers, tourists, or families visiting the Ashanti Region. The property features modern amenities, a well-equipped kitchen, and a homely atmosphere. Located near KNUST, shopping centers, and major commercial areas, this is perfect for short-term rentals. The area is quiet, secure, and offers easy access to Kumasi's attractions and business districts.",
    amenities: [
      "Fully Furnished",
      "Self-Catering Kitchen",
      "Air Conditioners",
      "DSTV/Netflix Ready",
      "WiFi Included",
      "All Bedrooms En-suite",
      "Living and Dining Areas",
      "Washing Machine",
      "Generator Backup",
      "Gated Compound Security",
      "Parking Space",
      "Daily Cleaning Available",
      "Prepaid Meter"
    ],
    status: "For Rent",
    propertyType: "Short Stays",
    featured: false
  },
  {
    id: 29,
    title: "Urban Charm, Easy Price",
    price: "$287,000",
    location: "Tse Addo, Accra",
    bedrooms: 3,
    bathrooms: 3,
    area: "285 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t12.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Charming 3-bedroom home in the established Tse Addo neighborhood. This property offers solid construction, practical layout, and good value in a well-located area. Perfect for young professionals, small families, or as an investment property in inner-city Accra. Tse Addo benefits from proximity to the airport, commercial centers, and major roads, while maintaining a residential character. The home features all bedrooms en-suite, a functional kitchen, and adequate parking space.",
    amenities: [
      "Strategic Location",
      "Walled Compound",
      "Security Gate",
      "All Bedrooms En-suite",
      "Kitchen with Cabinets",
      "Guest Washroom",
      "Tiled Throughout",
      "Water Storage Tank",
      "Generator Provision",
      "2-Car Parking",
      "Front Porch",
      "Boys' Quarters",
      "Close to Airport"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 30,
    title: "Hill Breeze Executive Lodge",
    price: "$550/month",
    location: "Apowa, Takoradi",
    bedrooms: 2,
    bathrooms: 2,
    area: "370 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t17.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Affordable 2-bedroom apartment in Apowa, a residential area of Takoradi. This well-maintained unit offers comfortable living spaces with both bedrooms en-suite, a functional kitchen, and a decent living area. Perfect for professionals in the oil and gas industry, young couples, or small families seeking budget-friendly accommodation in the Western Region capital. The area provides good access to the harbor, commercial centers, and the beach, with reliable utilities and growing amenities.",
    amenities: [
      "Secure Compound",
      "Both Bedrooms En-suite",
      "Kitchen Space",
      "Living/Dining Area",
      "Guest Washroom",
      "Tiled Floors",
      "Water Storage",
      "Generator Backup",
      "Parking Space",
      "Balcony",
      "Prepaid Meter",
      "Good Road Access"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 31,
    title: "La Vida Executive Suites",
    price: "$2,300/month",
    location: "Pokuase, Accra",
    bedrooms: 3,
    bathrooms: 4,
    area: "515 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t24.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Spacious 3-bedroom executive apartment in the expanding Pokuase district. This well-appointed property features modern finishes, generous room sizes, and an extra bathroom for convenience. Perfect for professionals and families who want suburban tranquility while staying connected to Accra. Pokuase has seen major infrastructure upgrades including the new Pokuase Interchange, improving access to the city center. The apartment offers comfortable living spaces, a modern kitchen, and quality construction throughout.",
    amenities: [
      "Gated Community",
      "24-Hour Security",
      "All Bedrooms En-suite",
      "Guest Washroom",
      "Modern Fitted Kitchen",
      "Spacious Living Area",
      "Generator Backup",
      "Water Storage System",
      "Covered Parking for 2 Cars",
      "Balcony",
      "Tiled Throughout",
      "Prepaid Meter",
      "DSTV Ready"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 32,
    title: "Starter Smart Home",
    price: "$168,000",
    location: "Kwahu-Mpraeso",
    bedrooms: 2,
    bathrooms: 2,
    area: "210 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t22.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Perfect starter home in the beautiful mountain town of Kwahu-Mpraeso. This compact 2-bedroom property offers affordable homeownership in one of Ghana's most scenic locations. Known for its cool climate and the famous Kwahu Paragliding Festival, Mpraeso is ideal for retirees, vacation homes, or tourism investments. The property features modern construction, both bedrooms en-suite, and sits on a plot with potential for gardening. Experience mountain living with fresh air and a peaceful environment.",
    amenities: [
      "Mountain Location",
      "Cool Climate",
      "Both Bedrooms En-suite",
      "Modern Kitchen",
      "Living/Dining Area",
      "Tiled Floors",
      "Water Storage",
      "Security Fence",
      "Front Porch",
      "Garden Space",
      "Parking Space",
      "Own Plot Title"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 33,
    title: "4-Bedroom Semidetached Duplex with BQ",
    price: "$280,000",
    location: "Oyoko, Koforidua",
    bedrooms: 4,
    bathrooms: 4,
    area: "275 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t20.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Modern 4-bedroom semidetached duplex in Oyoko, one of Koforidua's prime residential areas. This property features two floors of well-designed living space plus a self-contained boys' quarters. The duplex design offers privacy between living areas with bedrooms on the upper floor. Oyoko is known for quality schools, proximity to the Koforidua Golf Club, and a serene environment. Perfect for families seeking a peaceful lifestyle in the Eastern Region with easy access to Accra via the motorway.",
    amenities: [
      "Semidetached Design",
      "Duplex Layout",
      "All Bedrooms En-suite",
      "Boys' Quarters (Self-Contained)",
      "Modern Kitchen",
      "Guest Washroom",
      "Living and Dining Areas",
      "Balcony",
      "Tiled Throughout",
      "Water Storage Tank",
      "Generator Provision",
      "Parking for 3 Cars",
      "Walled Compound"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 34,
    title: "Mistwood Lodge",
    price: "$2,590/month",
    location: "Afienya",
    bedrooms: 4,
    bathrooms: 4,
    area: "520 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t21.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Luxurious 4-bedroom rental property in the rapidly developing Afienya area. This spacious home offers generous living spaces, modern amenities, and a tranquil setting away from city congestion. Afienya has become increasingly popular due to improved infrastructure and proximity to both Accra and Tema. The property features quality construction, all bedrooms en-suite, and sits on a large compound with landscaping potential. Perfect for executives seeking space and comfort at a reasonable rental price.",
    amenities: [
      "Spacious Compound",
      "24-Hour Security",
      "All Bedrooms En-suite",
      "Modern Fitted Kitchen",
      "Family Living Area",
      "Guest Washroom",
      "Generator Backup",
      "Borehole Water",
      "Air Conditioning Ready",
      "Covered Parking",
      "Garden Space",
      "Boys' Quarters",
      "Paved Driveway"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 35,
    title: "Prestige Grove Apartments",
    price: "$730/month",
    location: "Dodowa, Accra",
    bedrooms: 2,
    bathrooms: 2,
    area: "470 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t15.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Affordable 2-bedroom apartment in Dodowa, a growing residential area on the Accra plains. This property offers good value for money with modern finishes, both bedrooms en-suite, and adequate living space. Dodowa provides a quieter alternative to city living while maintaining reasonable access to Accra and Tema. The area features improving infrastructure, markets, schools, and healthcare facilities. Ideal for young professionals, couples, or small families seeking budget-friendly accommodation with room to breathe.",
    amenities: [
      "Secure Compound",
      "Both Bedrooms En-suite",
      "Kitchen with Cabinets",
      "Living/Dining Area",
      "Guest Washroom",
      "Tiled Floors",
      "Water Storage",
      "Generator Backup",
      "Parking Space",
      "Balcony",
      "Prepaid Meter",
      "Good Road Access"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 36,
    title: "Cozy Holiday Home",
    price: "$1,590/month",
    location: "Patasi, Kumasi",
    bedrooms: 5,
    bathrooms: 5,
    area: "270 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t18.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Spacious 5-bedroom short-stay property in Patasi, a residential suburb of Kumasi. This home is perfect for families visiting the Ashanti Region, groups attending events, or corporate housing needs. The property offers comfortable accommodation with all bedrooms en-suite, a large living area, and a fully equipped kitchen. Patasi is close to major hotels, the Kumasi Sports Stadium, and commercial areas. Ideal for extended stays, family gatherings, or as a base for exploring Ghana's cultural capital.",
    amenities: [
      "Fully Furnished",
      "All Bedrooms En-suite",
      "Self-Catering Kitchen",
      "Large Living/Dining Area",
      "Air Conditioners",
      "DSTV Connection",
      "WiFi Available",
      "Generator Backup",
      "Gated Compound",
      "Parking for 3 Cars",
      "Laundry Facilities",
      "Housekeeping Available",
      "Guest Washroom"
    ],
    status: "For Rent",
    propertyType: "Short Stays",
    featured: false
  },
  {
    id: 37,
    title: "Affordable Comfort",
    price: "$215,000",
    location: "Dzorwulu, Accra",
    bedrooms: 3,
    bathrooms: 3,
    area: "230 sq m",
    image: "https://images.pexels.com/photos/1974596/pexels-photo-1974596.jpeg",
    additionalImages: ["", "", "", "", ""],
    description: "Well-located 3-bedroom home in Dzorwulu, one of Accra's established middle-class neighborhoods. This property offers solid construction and functional design at a competitive price. Dzorwulu benefits from proximity to Ring Road, shopping centers, hospitals, and international schools. The area has reliable utilities, good security, and mature infrastructure. Perfect for first-time buyers, young families, or investors seeking rental income in a strategic location with strong tenant demand.",
    amenities: [
      "Strategic Location",
      "All Bedrooms En-suite",
      "Kitchen with Cabinets",
      "Guest Washroom",
      "Living/Dining Areas",
      "Tiled Throughout",
      "Water Storage Tank",
      "Security Fence",
      "Generator Provision",
      "Parking for 2 Cars",
      "Front Porch",
      "Close to Major Roads"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 38,
    title: "Emerald Crest Living",
    price: "$3,550/month",
    location: "East Airport, Accra",
    bedrooms: 5,
    bathrooms: 6,
    area: "385 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t23.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Premium 5-bedroom luxury rental in the exclusive East Airport residential area. This sophisticated property features contemporary design, high-end finishes, and top-tier amenities throughout. Located in Accra's diplomatic zone near embassies, international schools, and upscale shopping, this home offers ultimate convenience for expatriates and senior executives. The property includes smart home features, landscaped gardens, and staff accommodation. Experience refined living in one of Ghana's most prestigious neighborhoods.",
    amenities: [
      "Prime Location",
      "24/7 Security Service",
      "All Bedrooms En-suite",
      "Master Suite with Dressing Room",
      "Gourmet Kitchen",
      "Home Office",
      "Entertainment Room",
      "Central Air Conditioning",
      "Solar + Generator Power",
      "CCTV Surveillance",
      "Landscaped Garden",
      "Swimming Pool",
      "2 Staff Quarters",
      "2-Car Garage"
    ],
    status: "For Rent",
    propertyType: "Luxury Homes",
    featured: true
  },
  {
    id: 39,
    title: "Luxurious 3 Bedroom House",
    price: "$275,000",
    location: "Ogbodjo, Accra",
    bedrooms: 3,
    bathrooms: 2,
    area: "270 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u1.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Quality 3-bedroom home in the developing Ogbodjo area. This property offers modern construction with spacious rooms, good finishes, and practical design. While Ogbodjo is still emerging, it provides affordable homeownership in Greater Accra with improving infrastructure and road access. The home features two bathrooms, a functional kitchen, and adequate compound space. An excellent opportunity for buyers seeking value in a growing neighborhood with capital appreciation potential.",
    amenities: [
      "Modern Construction",
      "3 Spacious Bedrooms",
      "2 Bathrooms",
      "Modern Kitchen",
      "Living/Dining Area",
      "Guest Washroom",
      "Tiled Floors",
      "Water Storage",
      "Security Fence",
      "Parking Space",
      "Front Porch",
      "Room for Extension"
    ],
    status: "For Sale",
    propertyType: "Luxury Homes",
    featured: false
  },
  {
    id: 40,
    title: "Legacy Twin Homes",
    price: "$1,150/month",
    location: "Pokuase, Accra",
    bedrooms: 2,
    bathrooms: 2,
    area: "575 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t26.jfif",
    additionalImages: ["", "", "", "", ""],
    description: "Spacious 2-bedroom apartment on generous land in Pokuase. This rental property offers more space than typical apartments, with a large compound perfect for outdoor activities or gardening. The location benefits from the new Pokuase Interchange, significantly improving access to central Accra. The apartment features both bedrooms en-suite, a modern kitchen, and comfortable living spaces. Ideal for families who want suburban space at an affordable rental rate, or professionals seeking a home office setup.",
    amenities: [
      "Large Compound (575 sqm)",
      "Both Bedrooms En-suite",
      "Modern Kitchen",
      "Spacious Living Area",
      "Guest Washroom",
      "Tiled Throughout",
      "Water Storage",
      "Generator Provision",
      "Parking for Multiple Cars",
      "Garden Space",
      "Security Fence",
      "Improved Road Access"
    ],
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 41,
    title: "Budget Bliss Home",
    price: "$355,000",
    location: "Abuakwa, Kumasi",
    bedrooms: 4,
    bathrooms: 5,
    area: "450 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u3.jfif",
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 42,
    title: "Cozy 4 Bedroom House",
    price: "$318,000",
    location: "New Achimota, Accra",
    bedrooms: 4,
    bathrooms: 3,
    area: "235 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u8.jfif",
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 43,
    title: "The Logan Park Villa",
    price: "$880/month",
    location: "Asokore Mampong, Kumasi",
    bedrooms: 3,
    bathrooms: 3,
    area: "340 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u5.jfif",
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 44,
    title: "Safari Ridge Executive Home",
    price: "$420,000",
    location: "Peduase",
    bedrooms: 4,
    bathrooms: 4,
    area: "325 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u6.jfif",
    status: "For Sale",
    propertyType: "Luxury Homes",
    featured: false
  },
  {
    id: 45,
    title: "Oakline Urban Suites",
    price: "$2,250/month",
    location: "Ashaley Botwe, Accra",
    bedrooms: 2,
    bathrooms: 2,
    area: "380 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t27.jfif",
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 46,
    title: "Urban 3 Bedroom House",
    price: "$275,000",
    location: "Oyibi, Accra",
    bedrooms: 3,
    bathrooms: 3,
    area: "290 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u4.jfif",
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 47,
    title: "Savvy 2 Bedroom Airbnb",
    price: "$225/night",
    location: "Lashibi, Accra",
    bedrooms: 2,
    bathrooms: 2,
    area: "145 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u10.jfif",
    status: "For Rent",
    propertyType: "Short Stays",
    featured: false
  },
  {
    id: 48,
    title: "Calm Meets Class",
    price: "$315,000",
    location: "Akosombo",
    bedrooms: 4,
    bathrooms: 4,
    area: "260 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u12.jfif",
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 49,
    title: "Lakeside Cozy Airbnb Retreat",
    price: "$250/night",
    location: "Lakeside Estate, Accra",
    bedrooms: 2,
    bathrooms: 3,
    area: "75 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u9.jfif",
    status: "For Rent",
    propertyType: "Short Stays",
    featured: false
  },
  {
    id: 50,
    title: "Golden Horizon Homes",
    price: "$220/month",
    location: "Pobiman, Accra",
    bedrooms: 1,
    bathrooms: 1,
    area: "410 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u2.jfif",
    status: "For Rent",
    propertyType: "Apartments",
    featured: false
  },
  {
    id: 51,
    title: "Value Gate Airbnb",
    price: "$235/night",
    location: "Adenta, Accra",
    bedrooms: 2,
    bathrooms: 2,
    area: "200 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t14.jfif",
    status: "For Rent",
    propertyType: "Short Stays",
    featured: false
  },
  {
    id: 52,
    title: "Family Grove",
    price: "$233,000",
    location: "Tarkwa",
    bedrooms: 4,
    bathrooms: 3,
    area: "310 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/t5.jfif",
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 53,
    title: "Budget Bliss Home",
    price: "$165,000",
    location: "Abuakwa, Kumasi",
    bedrooms: 3,
    bathrooms: 3,
    area: "340 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/s3.jpg",
    additionalImages: ["", "", "", "", ""],
    description: "This charming 3-bedroom home in Abuakwa, Kumasi offers exceptional value for first-time homebuyers and investors. The property sits on a generous plot with room for expansion, featuring a functional layout with all bedrooms en-suite. The neighborhood is quiet, safe, and family-friendly, with easy access to schools, markets, and the city center. This is an excellent opportunity to own property in Ghana's cultural capital at an affordable price point.",
    amenities: [
      "Walled Compound",
      "Security Gate",
      "All Bedrooms En-suite",
      "Guest Washroom",
      "Kitchen with Cabinets",
      "Tiled Floors",
      "Water Storage",
      "Parking for 2 Cars",
      "Front Porch",
      "Back Garden Space",
      "Outer Buildings Room"
    ],
    status: "For Sale",
    propertyType: "Private Homes",
    featured: false
  },
  {
    id: 54,
    title: "Beliz Airbnb Studio",
    price: "$115/night",
    location: "Tesano, Accra",
    bedrooms: 1,
    bathrooms: 1,
    area: "125 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/s1.jpg",
    status: "For Rent",
    propertyType: "Short Stays",
    featured: false
  },
  {
    id: 55,
    title: "Ocean Breeze Holiday Home",
    price: "$2,520/month",
    location: "Ada Foah",
    bedrooms: 4,
    bathrooms: 4,
    area: "315 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/u13.jfif",
    status: "For Rent",
    propertyType: "Short Stays",
    featured: false
  },
  {
    id: 56,
    title: "Prime Executive Office Suite",
    price: "$8,800/month",
    location: "Dzorwulu, Accra",
    washrooms: 12,
    area: "465 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v2.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 57,
    title: "80 Square Meter Office Space ",
    price: "$520/month",
    location: "Teshie-Nungua, Accra",
    washrooms: 1,
    area: "80 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v9.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 58,
    title: "Open Plan Office Plaza",
    price: "$3,300/month",
    location: "Ridge, Accra",
    washrooms: 5,
    area: "250 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v3.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 59,
    title: "Newly Built Commercial Office Space",
    price: "$850/month",
    location: "Westlands, Accra",
    washrooms: 1,
    area: "85 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v5.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 60,
    title: "120 Square Meter Office Unit",
    price: "$800/month",
    location: "Kwadaso, Kumasi",
    washrooms: 2,
    area: "120 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/w1.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 61,
    title: "Agbi Tower Top-Floor Space",
    price: "$3,200/month",
    location: "Spintex, Accra",
    washrooms: 4,
    area: "415 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/w6.jpg",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 62,
    title: "Office Space To Let",
    price: "$620/month",
    location: "Madina, Accra",
    washrooms: 1,
    area: "70 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v8.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 63,
    title: "Corporate Office FLoors For Rent",
    price: "$2,100/month",
    location: "Labone, Accra",
    washrooms: 6,
    area: "300 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v1.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: true
  },
  {
    id: 64,
    title: "Private Office Space",
    price: "$180/month",
    location: "Ashaley Botwe, Accra",
    washrooms: 1,
    area: "45 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/w4.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 65,
    title: "Two-Room Office Unit",
    price: "$780/month",
    location: "Baatsona, Accra",
    washrooms: 1,
    area: "140 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/w3.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 66,
    title: "Ground Floor Office Space",
    price: "$1,300/month",
    location: "Dansoman, Accra",
    washrooms: 2,
    area: "165 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/w2.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 67,
    title: "Compact Office Room",
    price: "$430/month",
    location: "Agbogba, Accra",
    washrooms: 1,
    area: "65 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v7.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 68,
    title: "Modern Office Space To Let",
    price: "$755/month",
    location: "Abelemkpe, Accra",
    washrooms: 1,
    area: "70 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v4.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 69,
    title: "Semi-Furnished Office Space Near Mall",
    price: "$1,850/month",
    location: "Shiashie, Accra",
    washrooms: 2,
    area: "205 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/w9.jpg",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 70,
    title: "Prime Located Commercial Office",
    price: "$1,100/month",
    location: "Achimota, Accra",
    washrooms: 2,
    area: "130 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/w5.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  },
  {
    id: 71,
    title: "Simple Corporate Office Space",
    price: "$270/month",
    location: "Tech-Junction, Kumasi",
    washrooms: 1,
    area: "85 sq m",
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/v6.jfif",
    status: "For Rent",
    propertyType: "Commercial",
    featured: false
  }













];

export const testimonials = [
  {
    id: 1,
    name: "Sarah Adaklu",
    role: "Happy Homeowner",
    image: "https://raw.githubusercontent.com/Webeddies/reviewer-images/refs/heads/main/review-1.jpg",
    text: "Eddie Realty made our dream home a reality. Their expertise and dedication throughout the entire process was exceptional, not forgetting Ella's sense of humor!"
  },
  {
    id: 2,
    name: "Ohene Wiredu",
    role: "Property Investor",
    image: "https://raw.githubusercontent.com/Webeddies/reviewer-images/refs/heads/main/review%202.jpeg",
    text: "Just two words; professional and reliable. I had doubts at first, but Cobbs, together with the team, helped me find the perfect investment properties after returning to Ghana a few months ago."
  },
  {
    id: 3,
    name: "Jessica Allotey",
    role: "First-time Buyer",
    image: "https://raw.githubusercontent.com/Webeddies/reviewer-images/refs/heads/main/review%203.jpg",
    text: "As a first-time buyer, I had no idea what to expect. Their team was patient, explained everything clearly, and even took me on a site tour. I’m now a proud landowner in Oyibi and I’m already planning my second investment with them."
  },
  {
    id: 4,
    name: "Youssef Amad",
    role: "Luxury Home Seller",
    image: "https://raw.githubusercontent.com/Webeddies/reviewer-images/refs/heads/main/review%204.jpg",
    text: "I rarely put my business in the hands of agents but they sold our luxury home in record time and at a price that exceeded our expectations. Truly impressive work."
  }
];

export const agents = [
  {
    id: 1,
    name: "Lawrence Cobbinah",
    title: "Senior Real Estate Agent",
    experience: "13 Years",
    specialties: ["Luxury Homes", "Investment Properties", "Land Broker"],
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/agent%204.jpg",
    phone: "+1 (555) 987 6522/ +233 (0) 506 878 112",
    email: "lawcobbinah600@eddierealty.com",
    listings: 19
  },
  {
    id: 2,
    name: "Raphaella Deladem Adzei",
    title: "Residential Property Expert",
    experience: "7 Years",
    specialties: ["Family Homes", "Apartments", "First-time Buyers"],
    image: "https://raw.githubusercontent.com/Webeddies/Real-Estate-Agents/refs/heads/main/agent%203.jpg",
    phone: "+44 (0)7123 456 789/ +233 (0) 241 993 713",
    email: "phaella55@eddierealty.com",
    listings: 27
  },
  {
    id: 3,
    name: "Robert Finney-Smith",
    title: "Commercial Real Estate Specialist",
    experience: "10 Years",
    specialties: ["Commercial", "Industrial",],
    image: "https://raw.githubusercontent.com/Webeddies/Real-Estate-Agents/refs/heads/main/agent%202.jpg",
    phone: "+1 (555) 234 5678/ +233 (0) 548 088 000",
    email: "finneysmith005@eddierealty.com",
    listings: 7
  },
  {
    id: 4,
    name: "Amanda Foster",
    title: "Short Term Rental Expert",
    experience: "4 Years",
    specialties: ["Airbnbs", "Vacation Rentals"],
    image: "https://raw.githubusercontent.com/Webeddies/Real-Estate-Agents/refs/heads/main/agent%201.jpg",
    phone: "+233 (0) 594 400 878",
    email: "amandafoster808@eddierealty.com",
    listings: 9
  },
  {
    id: 5,
    name: "Wilberforce K. Peprah",
    title: "Land Broker",
    experience: "6 Years",
    specialties: ["Commercial", "Land Broker"],
    image: "https://raw.githubusercontent.com/Webeddies/Properties/refs/heads/main/agent%205.jpg",
    phone: "+233 (0) 265 144 374/ +233 (0) 557 795 353",
    email: "kwilbs211@eddierealty.com",
    listings: 9
  }
];

export const blogPosts = [
  {
    id: 1,
    title: "Market Trends: What to Expect in 2025",
    excerpt: "Discover the latest real estate market trends and predictions for the year.",
    image: "https://raw.githubusercontent.com/webeddies/real-estate-items-/refs/heads/main/market%20insights.jpg",
    date: "January 22, 2025",
    category: "Market Insights",
    link: "https://www.africahousingnews.com/17-strong-forecasts-for-real-estate-in-ghana-in-2025/",
    readTime: "20 min read"
  },
  {
    id: 2,
    title: "First-Time Buyer's Complete Guide",
    excerpt: "Everything you need to know about buying your first home in Ghana, from financing to closing.",
    image: "https://www.globalpropertiesafrica.com/propertygallery/74648939243eb68f51eeef2a9bb4e4f3250f2a0fc.jpg",
    date: "November 9, 2023",
    category: "Buying Tips",
    link: "https://thegreensgh.com/homebuying-in-ghana-for-first-time-buyers/",
    readTime: "5 min read"
  },
  {
    id: 3,
    title: "Investment Properties: Maximizing ROI",
    excerpt: "Learn strategies for selecting and managing investment properties for optimal returns.",
    image: "https://raw.githubusercontent.com/webeddies/real-estate-items-/refs/heads/main/Maximizing%20ROI.jpg",
    date: "January 6, 2020",
    category: "Investment",
    link: "https://www.forbes.com/councils/forbesrealestatecouncil/2020/01/06/six-strategies-for-maximizing-income-through-your-rental-property-investment/",
    readTime: "6 min read"
  },
  {
    id: 4,
    title: "Selling Your Home Faster: Proven Tips",
    excerpt: "Learn how to prepare your home for sale and attract the right buyers quickly.",
    image: "https://raw.githubusercontent.com/webeddies/Properties/refs/heads/main/t5.jfif",
    date: "February 14, 2024",
    category: "Selling Tips",
    link: "https://www.opendoor.com/blog/home-selling/tips-for-selling-your-home-faster",
    readTime: "7 min read"
  },
  {
    id: 5,
    title: "Hidden Costs of Buying a Home",
    excerpt: "From legal fees to inspections, understand the extra costs beyond the listing price.",
    image: "https://raw.githubusercontent.com/webeddies/Properties/refs/heads/main/s6.jpg",
    date: "March 3, 2024",
    category: "Buying Tips",
    link: "https://www.investopedia.com/articles/mortgages-real-estate/08/hidden-costs-home.asp",
    readTime: "4 min read"
  },
  {
    id: 6,
    title: "Land Ownership in Ghana: What You Must Know",
    excerpt: "Avoid common legal mistakes when acquiring land. Know your rights and documentation.",
    image: "https://raw.githubusercontent.com/webeddies/real-estate-items-/refs/heads/main/land%20dodowa.jfif",
    date: "October 12, 2023",
    category: "Investment",
    link: "https://www.modernghana.com/news/1134321/acquiring-land-in-ghana-know-the-right-steps-to.html",
    readTime: "8 min read"
  },
  {
    id: 7,
    title: "2024 Real Estate Tax Updates in Ghana",
    excerpt: "Stay compliant and informed with the latest property tax changes and obligations.",
    image: "https://raw.githubusercontent.com/webeddies/real-estate-items-/refs/heads/main/tax%20files.jpg",
    date: "December 5, 2024",
    category: "Market Insights",
    link: "https://www.graphic.com.gh/news/general-news/ghana-news-what-you-should-know-about-property-rates.html",
    readTime: "6 min read"
  },
  {
    id: 8,
    title: "How to Stage a Home That Sells",
    excerpt: "Use lighting, furniture, and colors to present your home in the best possible way.",
    image: "https://raw.githubusercontent.com/webeddies/real-estate-items-/refs/heads/main/real%20est.jpg",
    date: "August 18, 2023",
    category: "Selling Tips",
    link: "https://www.zillow.com/sellers-guide/home-staging-tips/",
    readTime: "5 min read"
  }
];
export const propertyCategories = [
  {
    id: 1,
    name: "Apartments",

    description: "Modern apartments in prime locations",
    count: 16,
    types: ["Apartments"]
  },
  {
    id: 2,
    name: "Houses",

    description: "Family homes and luxury estates",
    count: 31,
    types: ["Luxury Homes", "Private Homes"]
  },
  {
    id: 3,
    name: "Commercial",

    description: "Office spaces and retail properties",
    count: 16,
    types: ["Commercial"]
  },
  {
    id: 4,
    name: "Lands",

    description: "Development plots and agricultural land",
    count: 0,
    types: ["Lands"]
  },
  {
    id: 5,
    name: "Short Stays",

    description: "Vacation rentals and short-term stays",
    count: 8,
    types: ["Short Stays"]
  }
];